version: '1.0'

services:
  queue-api:
    depends_on:
      - redis
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /node_modules
      - .:/services
    ports:
      - '3005:3005'
    environment:
      - REDIS_HOST=redis
      - DB_CONNECTION_STRING=mongodb://mongo:27017/user
    networks:
      - cache
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    networks:
      - cache
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - cache

networks:
  cache: {}

volumes:
  mongodb_data:
